services:
  db:
    image: postgres:15-alpine
    container_name: test2_aq_db_gift  # ✅ ตั้งชื่อ container ได้เลย
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - acaq_data:/var/lib/postgresql/data

volumes:
  acaq_data:
